[]{#sessions}

# Kolmanda taseme matemaatika sisu

## Arvutamine

### Õpitulemused

\multicolsbegin

Kursuse lõpus õpilane:

1. selgitab arvu ruutjuure tähendust;
2. leiab peast või taskuarvutil ruutjuure[@phikooli].

\multicolsend

## Kalender

### 2024-9-4

Tutvustasin juurimist.

Osalesid alekseid, artjom, svetlana, nikolai, maarja ja katja.

### 2024-9-4

Harjutasime juurimist.

### 2024-9-5

Käsitlesime uuesti kõike senikäsitletut juurimise osas minu slaidide abiga. Selgitasin juurimist paaritu- ja paarisarvulise juurijaga.

Osalesid vanem aleksei, artjom, svetlana, nikolai ja katja.

### 2024-9-5

Harjutasime juurimist: sõnastus, lahtikirjutamine.

### 2024-9-11

Vaatasime üle koduse ülesande lahendamise. Testisin õpilasi õpiväljundite suhtes.

Katja Spungina:
1. õpiväljund: 4,
2. õpiväljund: 5.

Maarja:
1. õpiväljund: 3,
2. õpiväljund: 2.

Artem:
1. õpiväljund: 1,
2. õpiväljund: 5.

Alexey Mazanob
1. õpiväljund: 4,
2. õpiväljund: 2.

Osalesid vanem aleksei, artjom, ilja, nikolai, maarja ja katja.

### 2024-9-11

Tutvustasin ruutvõrrandit: üldkuju, komponendid.

### 2024-9-12

Kordasime ruutvõrrandi üldkuju ja komponente, jaotasime võrrandid eri alamkategooriatesse.

Osalesid Katja Spungina, Maarja, Artem, Alexey Mazanob, nikolai ja ilja.

### 2024-9-12

Näitasin, kuidas ruutvõrrandit koostada ruudu külje ja ristküliku külje pikkuse arvutamiseks. Harjutasime lahendite kontrollimist.

### 2024-9-18

Lahendasime koduseid ülesandeid, mis olid ruutvõrrandi lahendite kontrollimise, tüübi ja koefitsientide määramise kohta.

### 2024-9-18

Asusime astendamist algusest peale käsitlema. Jätsin koju lahendada kuni nelja astmed.

Osalesid Katja Spungina, Maarja, Artem, Alexey Mazanob, nikolai ja ilja.

### 2024-9-19

Kirjutasime lahti astmeid väikese variatsiooniga.

### 2024-9-19

Kirjutasime lahti astmeid suure variatsiooniga. Tegin astendamise tabeli ühest kümneni astendatava osas ja ühest üheksani astendatava osas. Otsisime ühesugused astmed ja tegurdasime. Pärast tegime juurimised. Koju jätsin lahendada veel mõne arvupaari arvude tegurdamise ja pöördtehete tegemise.

Osalesid Katja Spungina, Maarja, Artem, Alexey Mazanob, nikolai ja ilja.

### 2024-9-25

Lahutasime teguriteks arvu 1296 ning visandasime neli teisendit selle arvu teguritepuust. Näitasin, kuidas astendada jagatist.

### 2024-9-25

Testisime, mis jäi külge astme tegurdamisest:
Kapitonenko. Sletlana: 30 / 52,
Maarja: 34 / 52,
Alexey Mazanov: 39 / 52,
Spungina Katja: 41 / 52,
Artem Slepnjov: 47 / 52.

Tegime läbi jagatise astendamise väikese variatsiooniga harjutusülesanded, mis jäid iseseisvalt lõpuni lahendada, kes ei jõudnud.

### 2024-9-26

Käsitlesin õpilaste tehtud vigu astendamise E-taseme testis. Alustasime negatiivse astendatava astendamise käsitlemist.

Osalesid Alexey Mazanov, Artem Slepnjov, nikolai ja svetlana.

### 2024-9-26

Harjutasime negatiivse astendatava astendamise käsitlemist.

Käsitlesime sama astendatavaga astendamist. Ülesanded, mille puhul oli ainult tulemus esitatud, jäid iseseisvaks lahendamiseks.
